simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('singup/', views.SingUp.as_view(), name='singup'),

]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>', views.UserPost.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name="delete")
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='post')),
    path('groups/', include('groups.urls', namespace='groups')),
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TECHster.</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}"
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar mynav navbar-expand-lg bg-dark navbar-dark" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">TECHster.</a> 
            
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="https://github.com/GeoBruit/TECHster-Project" target="_blank">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                            </svg>
                        </a>
                    </li>
                    <li  class="nav-item">
                        <a class="nav-link active" href="{% url 'posts:create' %}">Post</a>
                    </li>
                    <li  class="nav-item">
                        <a class="nav-link active" href="{% url 'groups:all' %}">Groups</a>
                    </li>
                    <li  class="nav-item">
                        <a class="nav-link active" href="{% url 'groups:create' %}">Create Group</a></li>
                    <li  class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:logout' %}">LogOut</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="https://github.com/GeoBruit/TECHster-Project" target="_blank">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                            </svg>
                        </a>
                    </li>
                    <li  class="nav-item">
                        <a class="nav-link active" href="{% url 'groups:all' %}">Groups</a>
                    </li>
                    <li  class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li  class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:singup' %}">SignUp</a>
                    </li>

                {% endif %}

            </ul>

        </div>
    </nav>
    <div class="container">
    {% block content %}

    {% endblock %}
    </div>


<canvas id="canvas"></canvas>
</body>
<script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}">
</script>
</html>

simplesocial/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to TECHster.</h1>
{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html' %}
{% block container %}
<h1> You are now loged in</h1>

{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}
{% block container %}
<h1> You are now loged out</h1>

{% endblock %}